select*from sales_data;
--Q1. What is the total revenue generated by male vs. female customers?

  select gender,sum("purchase_amount_(usd)") as revenue
  from sales_data
  group by gender;
  
--Q2. Which customers used a discount but still spent more than the average purchase amount?

  select customer_id,"purchase_amount_(usd)"
  from sales_data
  where discount_applied='yes' and ("purchase_amount_(usd)")>=(select avg("purchase_amount_(usd)")from sales_data)

   
--Q3. Which are the top 5 products with the highest average review rating?

  select item_purchased,avg(review_rating) as "average products rating"
  from sales_data
  group by item_purchased
  order by avg(review_rating) desc
  limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type,
round (avg ("purchase_amount_(usd)"),3)
from sales_data
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribed and non-subscribed customers?

select subscription_status,
round(avg("purchase_amount_(usd)"),2)as avg_spend,
round(sum("purchase_amount_(usd)"),2)as total_revenue,
count (customer_id)as total_customer
from sales_data
group by subscription_status
order by total_revenue,avg_spend desc;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,
round(sum(case when discount_applied='Yes' then 1 else 0 end)/count(*)::numeric * 100,3) as discount_rate
from sales_data
group by item_purchased
order by discount_rate desc
limit 5;

select*from sales_data;
--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases?

SELECT 
    CASE
        WHEN previous_purchases = 0 THEN 'New'
        WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM sales_data
GROUP BY customer_segment;
--Q8. What are the top 3 most purchased products within each category?

SELECT category, item_purchased, purchase_count
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(*) DESC
        ) AS rank
    FROM sales_data
    GROUP BY category, item_purchased
) t
WHERE rank <= 3
ORDER BY category, purchase_count DESC;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM sales_data
WHERE previous_purchases > 5
GROUP BY subscription_status;

--what is the revenue contribution of each age group?

SELECT 
    age_group,
    SUM("purchase_amount_(usd)") AS total_revenue
FROM sales_data
GROUP BY age_group
ORDER BY total_revenue DESC;

